# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'usansa.azurecr.io/dotnetcoremvc:$(build.buildId)'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerFile: NetCoreApp/Dockerfile
    imageName: '$(imageName)'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: '$(AzureSubscription)'
    azureContainerRegistry: usansa.azurecr.io
    command: 'Push an image'
    imageName: 'dotnetcoremvc:$(Build.BuildId)'